# Generated by Django 3.1.3 on 2021-01-03 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squirrelsite', '0002_redeemedscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedeemedScore',
            new_name='Redeemed',
        ),
    ]
