# Generated by Django 3.1.3 on 2021-01-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0003_auto_20210103_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeemed',
            old_name='puzle',
            new_name='puzzle',
        ),
    ]
