# Generated by Django 3.1.3 on 2021-01-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0004_auto_20210121_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
