# Generated by Django 3.1.3 on 2021-02-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0007_auto_20210218_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SquadMember',
        ),
    ]
