# Generated by Django 3.1.3 on 2021-02-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0008_delete_squadmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
