# Generated by Django 3.1.3 on 2021-02-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0009_squad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squad',
        ),
    ]
