# Generated by Django 3.1.3 on 2021-02-26 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0011_squad_squadmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemed',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 19, 13, 52, 412897, tzinfo=utc)),
        ),
    ]
