# Generated by Django 3.1.3 on 2021-02-26 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0012_redeemed_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemed',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
