# Generated by Django 3.1.3 on 2021-03-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelsite', '0013_auto_20210226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmember',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='squirrelsite.squad'),
        ),
    ]
